export const REGION_DATA = [
    { id: 'nurafshon', name: "Nurafshon sh", population: 54100 },
    { id: 'angren', name: "Angren sh", population: 191300 },
    { id: 'bekobod-sh', name: "Bekobod sh", population: 102000 },
    { id: 'chirchiq', name: "Chirchiq sh", population: 168000 },
    { id: 'olmaliq', name: "Olmaliq sh", population: 138500 },
    { id: 'ohangaron-sh', name: "Ohangaron sh", population: 42000 },
    { id: 'yangiyol-sh', name: "Yangiyo'l sh", population: 63000 },
    { id: 'oqqorgon', name: "Oqqo'rg'on t", population: 112400 },
    { id: 'ohangaron-t', name: "Ohangaron t", population: 108300 },
    { id: 'bekobod-t', name: "Bekobod t", population: 163400 },
    { id: 'bostonliq', name: "Bo'stonliq t", population: 175600 },
    { id: 'boka', name: "Bo'ka t", population: 132400 },
    { id: 'quyi-chirchiq', name: "Quyi chirchiq t", population: 115800 },
    { id: 'zangiota', name: "Zangiota t", population: 204300 },
    { id: 'yuqori-chirchiq', name: "Yuqori Chirchiq t", population: 142100 },
    { id: 'qibray', name: "Qibray t", population: 206800 },
    { id: 'parkent', name: "Parkent t", population: 153000 },
    { id: 'piskent', name: "Piskent t", population: 102400 },
    { id: 'orta-chirchiq', name: "O'rta Chirchiq t", population: 153500 },
    { id: 'chinoz', name: "Chinoz t", population: 147800 },
    { id: 'yangiyol-t', name: "Yangiyo'l t", population: 278300 },
    { id: 'toshkent-t', name: "Toshkent t", population: 194500 },
];
