INSERT INTO diseases (id, code, name, "reportFrequency", "isActive") VALUES
(gen_random_uuid(), '101', 'Ichterlama (virusli gepatit A)', 'MONTHLY', true),
(gen_random_uuid(), '102', 'Paratif A, B, C (Barcha)', 'MONTHLY', true),
(gen_random_uuid(), '103', 'Shu jumladan: paratif A', 'MONTHLY', true),
(gen_random_uuid(), '104', 'Paratif B', 'MONTHLY', true),
(gen_random_uuid(), '105', 'Ichterlamani va paratif bakteriyalarini tashuvchilar', 'MONTHLY', true),
(gen_random_uuid(), '106', 'Boshqa salmonellez infeksiyalari', 'MONTHLY', true),
(gen_random_uuid(), '107', 'Shu jumladan bakteriologik tasdiqlanganlar', 'MONTHLY', true),
(gen_random_uuid(), '108', 'Bakterial ichburug (shigelloz)', 'MONTHLY', true),
(gen_random_uuid(), '109', 'Shigelloz bakteriologik tasdiqlanganlar', 'MONTHLY', true),
(gen_random_uuid(), '110', 'Fleksner, Nyukal shigellasini keltirib chiqaradigan dizenteriya', 'MONTHLY', true),
(gen_random_uuid(), '111', 'Zonne shigellasini keltirib chiqaradigan dizenteriya', 'MONTHLY', true),
(gen_random_uuid(), '112', 'Dizenteriyada 1-guruh bakteriya tashuvchilar', 'MONTHLY', true),
(gen_random_uuid(), '113', 'Enteropatogen ichak tayoqchasini keltirib chiqaradigan kasalliklar', 'MONTHLY', true),
(gen_random_uuid(), '114', 'Virusli enterit, gastroenterit', 'MONTHLY', true),
(gen_random_uuid(), '115', 'Enteroviroz', 'MONTHLY', true),
(gen_random_uuid(), '116', 'Rotavirus infeksiyasi', 'MONTHLY', true),
(gen_random_uuid(), '117', 'Noaniq etiologiyali o''tkir ichak infeksiyasi', 'MONTHLY', true),
(gen_random_uuid(), '118', 'Shu jumladan: 2 yoshgacha bolalar', 'MONTHLY', true),
(gen_random_uuid(), '119', 'Vabo', 'MONTHLY', true),
(gen_random_uuid(), '120', 'Shu jumladan: vibrio tashuvchilar', 'MONTHLY', true),
(gen_random_uuid(), '121', 'Botulizm', 'MONTHLY', true),
(gen_random_uuid(), '122', 'Brutselloz', 'MONTHLY', true),
(gen_random_uuid(), '123', 'Shu jumladan yangidan aniqlangan', 'MONTHLY', true),
(gen_random_uuid(), '124', 'Leptospiroz', 'MONTHLY', true),
(gen_random_uuid(), '125', 'Epidemik parotit', 'MONTHLY', true),
(gen_random_uuid(), '126', 'Meningit (barcha)', 'MONTHLY', true),
(gen_random_uuid(), '127', 'Shu jumladan: bakterial meningit', 'MONTHLY', true),
(gen_random_uuid(), '128', 'Meningokokk infeksiyasi', 'MONTHLY', true),
(gen_random_uuid(), '129', 'So''zak', 'MONTHLY', true),
(gen_random_uuid(), '130', 'Zaxm', 'MONTHLY', true),
(gen_random_uuid(), '131', 'Shu jumladan: yangi aniqlangan', 'MONTHLY', true),
(gen_random_uuid(), '132', 'Gemorragik isitmalar (barcha)', 'MONTHLY', true),
(gen_random_uuid(), '133', 'Krym-Kongo gemorragik isitmasi', 'MONTHLY', true),
(gen_random_uuid(), '134', 'Leyshmaniyoz', 'MONTHLY', true),
(gen_random_uuid(), '135', 'Shu jumladan: teri leyshmaniyozi', 'MONTHLY', true),
(gen_random_uuid(), '136', 'Qizamiq', 'MONTHLY', true),
(gen_random_uuid(), '137', 'Epidemik ko''k ko''z (Rubella)', 'MONTHLY', true),
(gen_random_uuid(), '138', 'Qizil isitma', 'MONTHLY', true),
(gen_random_uuid(), '139', 'Bo''g''ma', 'MONTHLY', true),
(gen_random_uuid(), '140', 'Ko''k yo''tal', 'MONTHLY', true),
(gen_random_uuid(), '141', 'Shu jumladan: laboratoriya tasdiqlangan', 'MONTHLY', true),
(gen_random_uuid(), '142', 'Sil (yangi aniqlangan)', 'MONTHLY', true),
(gen_random_uuid(), '143', 'Shu jumladan: baliqlarda va hayvonlarda', 'MONTHLY', true),
(gen_random_uuid(), '144', 'Bezgak (barcha)', 'MONTHLY', true),
(gen_random_uuid(), '145', 'Virusli gepatit B (barcha)', 'MONTHLY', true),
(gen_random_uuid(), '146', 'Virusli gepatit C', 'MONTHLY', true),
(gen_random_uuid(), '147', 'Virusli gepatit D', 'MONTHLY', true),
(gen_random_uuid(), '148', 'Virusli gepatit E', 'MONTHLY', true),
(gen_random_uuid(), '149', 'Qaytalama isitma (borreliyoz)', 'MONTHLY', true),
(gen_random_uuid(), '150', 'Quturish', 'MONTHLY', true),
(gen_random_uuid(), '151', 'Quturish xavfi bor hayvonlar tishlaganlar', 'MONTHLY', true),
(gen_random_uuid(), '152', 'Sibir yarasi', 'MONTHLY', true),
(gen_random_uuid(), '153', 'Esherixioz', 'MONTHLY', true),
(gen_random_uuid(), '154', 'Toksikinfeksiya', 'MONTHLY', true),
(gen_random_uuid(), '155', 'Listerioz', 'MONTHLY', true),
(gen_random_uuid(), '156', 'Iyersinioz', 'MONTHLY', true),
(gen_random_uuid(), '157', 'Psevdotuberkulyoz', 'MONTHLY', true),
(gen_random_uuid(), '158', 'Kriptosporidioz', 'MONTHLY', true),
(gen_random_uuid(), '159', 'Giardioz (lyamblioz)', 'MONTHLY', true),
(gen_random_uuid(), '160', 'Entamobioz', 'MONTHLY', true),
(gen_random_uuid(), '161', 'Askaridioz', 'MONTHLY', true),
(gen_random_uuid(), '162', 'Enterobioz', 'MONTHLY', true),
(gen_random_uuid(), '163', 'Trikhuroz', 'MONTHLY', true),
(gen_random_uuid(), '164', 'Toksoplazmoz', 'MONTHLY', true),
(gen_random_uuid(), '165', 'Ekhinokokkoz', 'MONTHLY', true),
(gen_random_uuid(), '166', 'Tenioz', 'MONTHLY', true),
(gen_random_uuid(), '167', 'OITS (yangi aniqlangan HIV)', 'MONTHLY', true),
(gen_random_uuid(), '168', 'Koronavirus (COVID-19)', 'MONTHLY', true)
ON CONFLICT (code) DO NOTHING;
