INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('101', 'Ichterlama', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('102', 'Paratiflar A, B, C (Barchasi)', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('103', 'shu jumladan: paratif A', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('104', 'paratif B', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('105', 'Ichterlama va paratif bakteriyalarini tashuvchilari', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('106', 'Boshqa salmonellez infeksiyalari', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('107', 'shu jumladan bakteriologik tasdiqlanganlar', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('108', 'Bakterial ichburug'' (shigellez)', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('109', 'shu jumladan bakteriologik tasdiqlanganlar', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('110', 'Fleksner, Nyukasl shigellasi keltirib chiqargan', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('111', 'Zonne shigellasi keltirib chiqargan', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('112', 'Grigoryev-Shiga shigellasi keltirib chiqargan', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('113', 'Ichburug'' bakteriya tashuvchilari', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('114', 'Ierseniya enterokoliti keltirib chiqargan enteritlar', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('115', 'Aniqlangan qo''zg''atuvchilar sabab bo''lgan enterit, kolit, gastroenteritlar, ovqat toksikoinfeksiyalari', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('116', 'shu jumladan rotavirus infeksiyalar', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('117', 'Qo''zg''atuvchilari aniqlanmagan va aniq belgilanmagan o''tkir ichak infeksiyalari va ovqat toksikoinfeksiyalari', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('118', 'Tulyaremiya', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('119', 'Kuydirgi', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('120', 'Birinchi marta tashhisi aniqlangan brutsellez', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('121', 'Bo''g''ma', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('122', 'Bo''g''ma qo''zg''atuvchi toksigen shtammlari tashuvchilari', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('123', 'Ko''kyutal', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('124', 'Meningokokkli infeksiya', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('125', 'shu jumladan tarqoq turi', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('126', 'Qoqshol', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('127', 'O''tkir poliomielit', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('128', 'Suvchechak', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('129', 'Qizamiq', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('130', 'Bahor-yozgi kana entsefality', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('131', 'Skarlatina', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('132', 'Gemorragik isitma', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('133', 'Qizilcha', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('134', 'Tug''ma qizilcha', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('135', 'O''tkir virusli gepatit (jami)', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('136', 'shu jumladan gepatit A', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('137', 'gepatit B', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('138', 'gepatit C', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('139', 'gepatit E', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('140', 'gepatit D', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('141', 'Gepatit virusini tashuvchilar – birinchi marta aniqlanganlar – jami', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('142', 'ulardan Gepatit B (HBAg)', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('143', 'Gepatit C', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('144', 'Surunkali gepatitlar (birinchi marta aniqlanganlar)', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('145', 'Quturish', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('146', 'Ornitoz', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('147', 'Infeksion mononukleoz', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('148', 'Epidemik parotit', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('149', 'Rikketsiozlar', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('150', 'shu jumladan, epidemiya toshmali terlama', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('151', 'Brill kasalligi', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('152', 'Kanali toshma terlama', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('153', 'Qu isitmasi', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('154', 'Birinchi marta tashhisi aniqlangan bezgak', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('155', 'Bezgak parazitlarini tashuvchilar', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('156', 'Leptospiroz', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('157', 'Yuqori va quyi nafas olish yo''llari o''tkir infeksiyalari (O''RI)', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('158', 'Legionellez', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('159', 'Grippga o''xshash kasalliklar', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('160', 'O''tkir o''pka yallig''lanishi (Zotiljam)', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('161', 'Og''ir o''tkir respirator infeksiyalar (O''RI)', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('162', 'Sil (birinchi marta aniqlangan, barcha formasi)', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('163', 'shu jumladan bakteriya ajratish bilan (BK+)', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('164', '162-satrdan nafas olish a''zolari sili', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('165', 'shu jumladan bakteriya ajratish bilan (BK+)', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('166', 'Zahm (birinchi marta aniqlangan, barcha formasi)', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('167', 'O''tkir va surunkali suzak', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('168', 'Qotir', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('169', 'Pedikulez', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('170', 'Kanali qaytalama terlama', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('171', 'Askaridoz', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('172', 'Trikhotsefalloz (trikhuroz)', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('173', 'Enterobioz', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('174', 'Geminolipedoz', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('175', 'Tremadozlar', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('176', 'Exinokokkoz', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('177', 'Teniarinxoz (tenioz)', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('178', 'Trixofitiya', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('179', 'Mikrosporiya', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('180', 'Leyshmanioz', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('181', 'shu jumladan teri leyshmaniozi', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('182', 'Aniqlangan koronavirus infeksiyasi', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('183', 'Amiobioz', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('184', 'Balantidiaz', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('185', 'Jiardiaz (lyamblioz)', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('186', 'Kriptosporidioz', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('187', 'Izosporoz', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('201', 'Kasalxona ichki infeksiyalari – jami', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('202', 'shu jumladan – v tom chisle: Chaqaloqlardagi yiringli septik infeksiyalar: omfalit, mastit, konyuktivit, sepsis, piodermiya, impetigo, po''rsildoq yara, osteomielit', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('203', 'Tuqqan ayollardagi yiringli septik kasalliklar: sepsis, mastit, akusherlik yarasining jarrohlik amaliyotidan keyingi infeksiyasi, tug''ruqdan keyingi yoyilgan infeksiya va boshqalar', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('204', 'Operatsiyadan keyingi infeksiyalar: sepsis, abstsess, flegmona, inyeksiyadan keyingi sepsis, infuziyalar, perfuziyalar, transfuziyalar oqibatida yuz beradigan sepsis', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('205', 'Yuqori nafas olish yo''llarining o''tkir infeksiyalari', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('206', 'Siydik chiqarish yo''llari infeksiyalari', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('207', 'Aniqlangan va aniqlanmagan qo''zg''atuvchilar sabab bo''lgan o''tkir ichak infeksiyalari: enteritlar, kolitlar, gastroenteritlar, enterokolitlar', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('208', '106-satrdan boshqa salmonellez infeksiyalari', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('209', '137-satrdan virusli gepatit B', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;
INSERT INTO diseases (code, name, "reportFrequency", "isActive") VALUES ('210', 'Aniqlangan koronavirus infeksiyasi', 'MONTHLY', true) ON CONFLICT (code) DO NOTHING;