export const T1_ROWS = [
    { key: 'total', labelKey: 'children_hygiene.table1.rows.total', isBold: true, bgColor: '#ecfdf5' },
    { key: '1_1', labelKey: 'children_hygiene.table1.rows.1_1', isBold: true, color: '#e11d48' },
    { key: '1_1_1', labelKey: 'children_hygiene.table1.rows.1_1_1' },
    { key: '1_1_1_outsourcing', labelKey: 'children_hygiene.table1.rows.1_1_1_outsourcing' },
    { key: '1_1_2', labelKey: 'children_hygiene.table1.rows.1_1_2' },
    { key: '1_1_3', labelKey: 'children_hygiene.table1.rows.1_1_3' },
    { key: '1_1_4', labelKey: 'children_hygiene.table1.rows.1_1_4' },
    { key: '1_1_5', labelKey: 'children_hygiene.table1.rows.1_1_5' },
    { key: '1_1_7', labelKey: 'children_hygiene.table1.rows.1_1_7' },
    { key: '1_1_8', labelKey: 'children_hygiene.table1.rows.1_1_8' },
    { key: '1_2', labelKey: 'children_hygiene.table1.rows.1_2', isBold: true, color: '#e11d48' },
    { key: '1_2_1', labelKey: 'children_hygiene.table1.rows.1_2_1' },
    { key: '1_2_2', labelKey: 'children_hygiene.table1.rows.1_2_2' },
    { key: '1_2_3', labelKey: 'children_hygiene.table1.rows.1_2_3' },
    { key: '1_2_4', labelKey: 'children_hygiene.table1.rows.1_2_4' },
    { key: '1_3', labelKey: 'children_hygiene.table1.rows.1_3', isBold: true, color: '#e11d48' },
    { key: '1_3_1', labelKey: 'children_hygiene.table1.rows.1_3_1' },
    { key: '1_3_2', labelKey: 'children_hygiene.table1.rows.1_3_2' },
    { key: '1_3_3', labelKey: 'children_hygiene.table1.rows.1_3_3' },
    { key: '1_4', labelKey: 'children_hygiene.table1.rows.1_4', isBold: true, color: '#e11d48' },
    { key: '1_4_1', labelKey: 'children_hygiene.table1.rows.1_4_1' },
    { key: '1_5', labelKey: 'children_hygiene.table1.rows.1_5', isBold: true, color: '#e11d48' },
    { key: '1_5_1', labelKey: 'children_hygiene.table1.rows.1_5_1' },
    { key: '1_5_2', labelKey: 'children_hygiene.table1.rows.1_5_2' },
    { key: '1_5_3', labelKey: 'children_hygiene.table1.rows.1_5_3' },
    { key: '1_6', labelKey: 'children_hygiene.table1.rows.1_6', isBold: true, color: '#e11d48' },
    { key: '1_6_1', labelKey: 'children_hygiene.table1.rows.1_6_1' },
    { key: '1_6_1_pools', labelKey: 'children_hygiene.table1.rows.1_6_1_pools', isItalic: true },
    { key: '1_6_2', labelKey: 'children_hygiene.table1.rows.1_6_2' },
    { key: '1_6_3', labelKey: 'children_hygiene.table1.rows.1_6_3' },
    { key: '1_7', labelKey: 'children_hygiene.table1.rows.1_7', isBold: true, color: '#0369a1', bgColor: '#f0f9ff' },
    { key: '1_7_1', labelKey: 'children_hygiene.table1.rows.1_7_1', isItalic: true },
    { key: '1_7_2', labelKey: 'children_hygiene.table1.rows.1_7_2', isItalic: true },
    { key: '1_7_3', labelKey: 'children_hygiene.table1.rows.1_7_3', isItalic: true },
    { key: '1_7_4', labelKey: 'children_hygiene.table1.rows.1_7_4', isItalic: true },
    { key: '1_7_5', labelKey: 'children_hygiene.table1.rows.1_7_5', isItalic: true },
    { key: '1_7_6', labelKey: 'children_hygiene.table1.rows.1_7_6', isItalic: true },
    { key: '1_8', labelKey: 'children_hygiene.table1.rows.1_8', isBold: true, color: '#0369a1' },
];
