/** Jadval 2 uchun tuman qatorlari (rasmga mos tartibda) */
export const INSPECTION_T2_ROWS = [
    { key: "angren_sh", label: "Angren shahri" },
    { key: "bekobod_sh", label: "Bekobod shahri" },
    { key: "olmaliq_sh", label: "Olmaliq shahri" },
    { key: "ohangaron_sh", label: "Ohangaron shahri" },
    { key: "nurafshon_sh", label: "Nurafshon shahri" },
    { key: "chirchiq_sh", label: "Chirchiq shahri" },
    { key: "yangiyul_sh", label: "Yangiyo'l shahri" },
    { key: "bekobod_t", label: "Bekobod tumani" },
    { key: "bostonliq_t", label: "Bo'stonliq tumani" },
    { key: "buka_t", label: "Bo'ka tumani" },
    { key: "zangiota_t", label: "Zangiota tumani" },
    { key: "parkent_t", label: "Parkent tumani" },
    { key: "piskent_t", label: "Piskent tumani" },
    { key: "oqqorgon_t", label: "Oqqo'rg'on tumani" },
    { key: "ohangaron_t", label: "Ohangaron tumani" },
    { key: "toshkent_t", label: "Toshkent tumani" },
    { key: "qibray_t", label: "Qibray tumani" },
    { key: "quyi_chirchiq_t", label: "Quyi Chirchiq tumani" },
    { key: "orta_chirchiq_t", label: "O'rta Chirchiq tumani" },
    { key: "chinoz_t", label: "Chinoz tumani" },
    { key: "yuqori_chirchiq_t", label: "Yuqori Chirchiq tumani" },
    { key: "yangiyul_t", label: "Yangiyo'l tumani" },
    { key: "toshkent_viloyati", label: "Toshkent viloyati" },
];
