/** Jadval 2 uchun tuman qatorlari (rasmga mos tartibda) */
export const INSPECTION_T2_ROWS = [
    { key: "angren_sh", label: "Angren sh." },
    { key: "bekobod_sh", label: "Bekobod sh." },
    { key: "olmaliq_sh", label: "Olmaliq sh." },
    { key: "ohangaron_sh", label: "Ohangaron sh." },
    { key: "nurafshon_sh", label: "Nurafshon sh." },
    { key: "chirchiq_sh", label: "Chirchiq sh." },
    { key: "yangiyul_sh", label: "Yangiyo'l sh." },
    { key: "bekobod_t", label: "Bekobod t." },
    { key: "bostonliq_t", label: "Bo'stonliq t." },
    { key: "buka_t", label: "Bo'ka t." },
    { key: "zangiota_t", label: "Zangiota t." },
    { key: "parkent_t", label: "Parkent t." },
    { key: "piskent_t", label: "Piskent t." },
    { key: "oqqorgon_t", label: "Oqqo'rg'on t." },
    { key: "ohangaron_t", label: "Ohangaron t." },
    { key: "toshkent_t", label: "Toshkent t." },
    { key: "qibray_t", label: "Qibray t." },
    { key: "quyi_chirchiq_t", label: "Quyi Chirchiq t." },
    { key: "orta_chirchiq_t", label: "O'rta Chirchiq t." },
    { key: "chinoz_t", label: "Chinoz t." },
    { key: "yuqori_chirchiq_t", label: "Yuqori Chirchiq t." },
    { key: "yangiyul_t", label: "Yangiyo'l t." },
    { key: "toshkent_viloyati", label: "Toshkent viloyati" },
];
