export const NUTRITION_HYGIENE_T3_PRODUCTS = [
    { key: "meat_products", labelKey: "nutrition.t3.meat" },
    { key: "milk_products", labelKey: "nutrition.t3.milk" },
    { key: "fish_products", labelKey: "nutrition.t3.fish" },
    { key: "bread_products", labelKey: "nutrition.t3.bread" },
    { key: "sugar_products", labelKey: "nutrition.t3.sugar" },
    { key: "fruit_veg", labelKey: "nutrition.t3.fruit_veg" },
    { key: "fat_oil", labelKey: "nutrition.t3.fat_oil" },
    { key: "alcohol_soft", labelKey: "nutrition.t3.alcohol" },
    { key: "baby_food", labelKey: "nutrition.t3.baby_food" },
    { key: "canned_food", labelKey: "nutrition.t3.canned" },
    { key: "salt", labelKey: "nutrition.t3.salt" },
    { key: "other", labelKey: "nutrition.t3.other" },
];

export const NUTRITION_HYGIENE_DEFAULT_ROWS = [
    { key: "Angren sh", labelKey: "orgs.Angren sh" },
    { key: "Olmaliq sh", labelKey: "orgs.Olmaliq sh" },
    { key: "Chirchiq sh", labelKey: "orgs.Chirchiq sh" },
    { key: "Bekobod sh", labelKey: "orgs.Bekobod sh" },
    { key: "Ohangaron sh", labelKey: "orgs.Ohangaron sh" },
    { key: "Yangiyo'l sh", labelKey: "orgs.Yangiyo'l sh" },
    { key: "Nurafshon sh", labelKey: "orgs.Nurafshon sh" },
    { key: "Bo'stonliq t", labelKey: "orgs.Bo'stonliq t" },
    { key: "Oqqo'rg'on t", labelKey: "orgs.Oqqo'rg'on t" },
    { key: "Parkent t", labelKey: "orgs.Parkent t" },
    { key: "Piskent t", labelKey: "orgs.Piskent t" },
    { key: "Zangiota t", labelKey: "orgs.Zangiota t" },
    { key: "O'rta Chirchiq t", labelKey: "orgs.O'rta Chirchiq t" },
    { key: "Bo'ka t", labelKey: "orgs.Bo'ka t" },
    { key: "Ohangaron t", labelKey: "orgs.Ohangaron t" },
    { key: "Chinoz t", labelKey: "orgs.Chinoz t" },
    { key: "Toshkent t", labelKey: "orgs.Toshkent t" },
    { key: "Quyi chirchiq t", labelKey: "orgs.Quyi chirchiq t" },
    { key: "Yuqori Chirchiq t", labelKey: "orgs.Yuqori Chirchiq t" },
    { key: "Bekobod t", labelKey: "orgs.Bekobod t" },
    { key: "Yangiyo'l t", labelKey: "orgs.Yangiyo'l t" },
    { key: "Qibray t", labelKey: "orgs.Qibray t" },
    { key: "Boshqarma", labelKey: "orgs.Boshqarma" },
    { key: "total", labelKey: "orgs.Jami" },
];
